export const termsAndConditions = `<p><strong>Precios.</strong> Los precios de los paquetes y servicios que ofrece el &ldquo;Car Wash&rdquo; pueden cambiar sin aviso. No se f&iacute;a ni se otorgan cr&eacute;ditos. Pagos con ATH M&oacute;vil se deber&aacute; presentar evidencia del pago. Se paga antes de otorgar el servicio o el <strong>50%</strong> del mismo. No todas las formas de pago ofertadas por &eacute;l &ldquo;Car Wash&rdquo; estar&aacute;n disponibles en todo momento. <strong><em>Servicios de Cita Previa</em></strong> deber&aacute;n pagar un deposito no reembolsable a la cita ya pautada, el porciento de este depender&aacute; del servicio solicitado.</p>
<p><strong>Descripci&oacute;n</strong>. Los servicios ofertados por el &ldquo;Car Wash&rdquo;, no necesariamente corresponden con la descripci&oacute;n de dicho servicio, si por alguna raz&oacute;n no se pudiera dar el servicio completo se le otorgara al cliente un servicio por un valor equivalente al promocionado, si el cliente no lo desea; se le otorgara un cup&oacute;n para canjearlo en otra fecha por la diferencia. &ldquo;Car Wash&rdquo; puede cambiar, modificar o cancelar sus servicios en cualquier momento.</p>
<p><strong>Horario.</strong> El horario publicado en la pagina de Facebook como en cartelones en el establecimiento no necesariamente ser&aacute; en forzado, puede el &ldquo;Car Wash&rdquo; cerrar el servicio sin previo aviso durante d&iacute;as festivos, fines de semana o cuando as&iacute; convenga sus intereses. El horario regular se publica de la pagina de Facebook.</p>
<p><strong>Riesgos.</strong> El &ldquo;Car Wash&rdquo; utiliza maquinas a presi&oacute;n, agua, qu&iacute;micos y aspiradoras, El cliente deber&aacute; de tomar sus precauciones e informar al lavador de cualquier condici&oacute;n especial que tenga su autom&oacute;vil.</p>
<p><strong>&Aacute;reas.</strong> El &ldquo;Car Wash&rdquo; ofrece &aacute;rea de espera adem&aacute;s de el &aacute;rea de enjuagado y secado. Las &aacute;reas comunes del Car Wash son de uso exclusivo de sus empleados. Las &aacute;reas de mantenimiento y de trabajo est&aacute;n prohibidas para los clientes, estas &aacute;reas no siempre est&aacute;n marcadas.</p>
<p>Si el cliente llegara a tener alg&uacute;n accidente en estas &aacute;reas, el &ldquo;Car Wash&rdquo; y sus empleados no se hace responsable de los da&ntilde;os que este pudiera llegar a tener.</p>
<p><strong>Generalidades.</strong> El consumo de drogas y bebidas alcoh&oacute;licas queda estrictamente prohibido y la administraci&oacute;n se reserva el derecho de admisi&oacute;n. Ni&ntilde;os menores de edad deber&aacute;n de estar siempre acompa&ntilde;ados por padres o supervisor.</p>
<p>No hay derecho de tanto ni preferencial a ning&uacute;n cliente, el orden con el que lleguen ser&aacute; con el que ser&aacute;n atendidos. Cualquier da&ntilde;o que el cliente genere a las instalaciones de, el &ldquo;Car Wash&rdquo; ser&aacute; responsabilidad del cliente.</p>
<p>Caf&eacute; y agua gratuita que se otorga en la sala de espera se limita a 1 taza o su equivalente por cliente, el &ldquo;Car Wash&rdquo; no se obliga a tener disponible esta cortes&iacute;a.</p>
<p>Si alg&uacute;n cliente se comporta de manera agresiva el servicio se cancelar&aacute; sin devoluci&oacute;n al cliente.</p>
<p><strong>Acerca del COVID-19</strong></p>
<p><strong>Uso de mascarilla en el establecimiento es completamente obligatorio y mantener los 6 pies de distancia.</strong></p>`